### ISSUE TITLE
files-get fails on default directory

### ISSUE THREAD

**Issue by georgebzheng** [TACC-Cloud/agave-cli#47]
After setting the default work directory, I tried the following command sequences:

----
(fcs-etl-reactor) MacBook-Pro:/Users/gzheng/projects/SD2/temp>files-list -L sd2e-data/my_copy.txt
-rw-------  gzheng  0  08:36  my_copy.txt
(fcs-etl-reactor) MacBook-Pro:/Users/gzheng/projects/SD2/temp>files-get sd2e-data/my_copy.txt

usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
(fcs-etl-reactor) MacBook-Pro:/Users/gzheng/projects/SD2/temp>
----

The second command works only with the -S flag.

**Comment by johnfonner** [comment]
The files-get command uses a different code path for files of zero size.  As part of that code path, it uses the "touch" command to create an empty file.  The actual line of code says `touch $filename`.  I'm not able to reproduce this error on my own machine.  What version of OS X do you have?  Would you try your files-get command again with the `-v` flag?  I suspect either $filename was somehow empty or something unexpected happened with the touch command itself.

**Comment by georgebzheng** [comment]
@mwes I just tried the same command again and it works now.  Please go ahead and close the issue.

**Comment by mwes** [comment]
@georgebzheng I can't close - you opened the issue, so you'll need to close. Thanks!

**Comment by georgebzheng** [comment]
@mwes I am closing the issue.
