### ISSUE TITLE
richtext.py has inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by georgebzheng** [TACC-Cloud/agave-cli#48]
Tried the following command:
profiles-search --rich --filter first_name,last_name,email.username 'email=gzheng@netrias.com'

and got 

(fcs-etl-reactor) MacBook-Pro:/Users/gzheng/projects/SD2/fcs-etl-reactor>profiles-search --rich --filter first_name,last_name,email,username 'email=juser@example.org'
jq: error (at <stdin>:1): Cannot index array with string "first_name"
jq: error (at <stdin>:1): Cannot index array with string "last_name"
jq: error (at <stdin>:1): Cannot index array with string "email"
jq: error (at <stdin>:1): Cannot index array with string "username"
File "/Users/gzheng/projects/SD2/sd2e-cloud-cli/bin/libs/python/richtext.py", line 20
print result
^
TabError: inconsistent use of tabs and spaces in indentation

After fixing the tab and print problems locally, I got the following output for the same command:

jq: error (at <stdin>:1): Cannot index string with string "username"
jq: error (at <stdin>:1): Cannot index array with string "email"
| first_name | last_name | email.username | 
| -----_---- | ----_---- | -------------- | 
| George     | Zheng     | null           |

**Comment by alejandrox1** [comment]
This script is used by a deprecated tool.
