### ISSUE TITLE
files-pems-list not working

### ISSUE THREAD

**Issue by georgebzheng** [TACC-Cloud/agave-cli#49]
files-pems-list fails to find files recognized by files-list:

(fcs-etl-reactor) MacBook-Pro:/Users/gzheng/projects/SD2/temp/reactors-etl/reactors/fastqc>files-list -L sd2e-data
drwx------  gzheng  4096  08:36  .
-rw-------  gzheng  0     08:36  my_copy.txt
-rw-------  gzheng  0     08:34  my_file.txt
(fcs-etl-reactor) MacBook-Pro:/Users/gzheng/projects/SD2/temp/reactors-etl/reactors/fastqc>files-pems-list sd2e-data/my_files.txt
File/folder does not exist

(fcs-etl-reactor) MacBook-Pro:/Users/gzheng/projects/SD2/temp/reactors-etl/reactors/fastqc>files-pems-list -S data-tacc-work-gzheng sd2e-data/my_files.txt
File/folder does not exist

**Comment by johnfonner** [comment]
Hi George,

From testing, files-pems-list is working as expected.  I think the issue with your command above is just a typo in the filename.  The file was `my_file.txt` (file singular) and your subsequent commands had `my_files.txt` as the name.

I'll close this issue for now.

Thanks,
John
